#!/usr/bin/env bash

set -eu -o pipefail

pushd build
ninja com.github.opensussex.scritch_app-pot
ninja com.github.opensussex.scritch_app-update-po
popd
if [[ $1 != '--no-status' ]]; then
  git status
fi

echo 'Translations updated.'
echo ''
echo 'Don’t forget to add and commit any'
echo 'new/changed files to your repository.'
